#####################################################################
# Codecov configuration.
#####################################################################
ignore:
    - "**/etc/.*"
    - "**/interfaces/.*"
    - "**/types/.*"
    - "**/*.spec.tsx"
    - "**/*.spec.ts"
    - "**/*.scss"
    - "**/*.svg"
    - "src/store/utils/.*"
