################################################################################
# Docker file for building base image for Listing Management Website
# in Production & Develop
#
# VERSION:
# 1.0.0 - initialization
################################################################################

FROM node:8.14.0-alpine

LABEL maintainer "kamila@99.co"

WORKDIR /app

EXPOSE 80

CMD [ "npm", "run", "dev" ]
